### ISSUE TITLE
Investigate and potentially add support for spark connect

### ISSUE THREAD

**Issue by razvan** [stackabletech/spark-k8s-operator#284]
## Spark Connect

Spark 3.5 introduces a new client called [Spark Connect](https://spark.apache.org/docs/latest/spark-connect-overview.html).

The use case seems to be thin clients that connect to a running spark driver.

This probably means that the operator needs to be able to start spark connect servers without spark applications and publish a service for "connect" clients.

## Roadmap

Rough roadmap to GA:

- [x] POC: can set up a spark-connect server with kubernetes as resource manager, basic integration test
- [x] minimal CRD: drop the stateful set, minimum configuration for the server (jvm props, logging)
   - [x] server
      - [x] deployment with one replica 
      - [x] jvm arg overrides
      - [x] config overrides
      - [x] env overrides
      - [x] log configuration and aggregation with vector
      - [x] pod overrides
      - [x] resource requests
      - [x] status and transition events
      - [x] reconciliation operation (paused, stopped, etc)
   - [x] executor 
      - [x] jvm arg overrides
      - [x] config overrides
      - [x] env overrides
      - [x] log configuration and aggregation 
      - [x] resource requests
      - [x] pod affinity
- [x] add preliminary documentation
- [x] expose Prometheus metrics  
- [x] ~~integrate with the history server~~ See: https://github.com/stackabletech/spark-k8s-operator/pull/559
- [x] integrate with the listener op
- [x] create a new demo

## Related PRs

- https://github.com/stackabletech/spark-k8s-operator/pull/539
- https://github.com/stackabletech/docker-images/pull/1034
- https://github.com/stackabletech/operator-rs/pull/992
- https://github.com/stackabletech/operator-rs/pull/993
- https://github.com/stackabletech/docker-images/pull/1051
- https://github.com/stackabletech/spark-k8s-operator/pull/559
- https://github.com/stackabletech/spark-k8s-operator/pull/562

**Comment by timrobertson100** [comment]
We have [started exploring](https://github.com/timrobertson100/spark-connect) Spark Connect at GBIF.org. Our primary use case is to explore having a long running spark cluster hold an in memory cached table, for apps to do filtered data egress with minimal startup cost.

**Comment by razvan** [comment]
@timrobertson100 - we merged preliminary support for spark connect deployments in the main branch. Looking forward for your feedback!

**Comment by dshershov** [comment]
Awesome! Good job guys!

**Comment by lfrancke** [comment]
@razvan This is in "Done" but not closed. Anything left to do?

Could you please add release notes and a link to the docs?

**Comment by razvan** [comment]
> This release adds experimental support for Spark Connect. The Spark operator watches for `SparkConnectServer` custom resources. Preliminary documentation is available here [1] and the existing Taxi Data Anomaly Detection demo [2] has been retrofitted to use a JupterLab client running against a Spark Connect server.
> 
> [1] https://docs.stackable.tech/home/nightly/spark-k8s/usage-guide/spark-connect/
> [2] https://docs.stackable.tech/home/nightly/demos/jupyterhub-pyspark-hdfs-anomaly-detection-taxi-data/

**Comment by timrobertson100** [comment]
Thank you very much. We have been watching but have not yet had time to test - it's on our backlog.
